approach: best_of_n

base_url: "http://localhost:30000"
api_key: "EMPTY"
max_threads: 4
model_path: null

verifier_type: "generative_verifier"
generative_verifier_template: "multi-turn"
generative_verifier_temperature: 0.0
verifier_score_weight: 2.0

exp_name: self-verify

n_samples: 4
dataset_path: data/math500.jsonl
dataset_size: null

temperature: 0.6
max_tokens: 2048

system_prompt: null
